// Package sast provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package sast

import (
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// CreateSastReport defines model for CreateSastReport.
type CreateSastReport struct {
	Description   string             `json:"description"`
	Name          string             `json:"name"`
	ReportContent string             `json:"reportContent"`
	Time          time.Time          `json:"time"`
	Uuid          openapi_types.UUID `json:"uuid"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// SastReport defines model for SastReport.
type SastReport struct {
	Description   string             `json:"description"`
	Name          string             `json:"name"`
	ReportContent string             `json:"reportContent"`
	Time          time.Time          `json:"time"`
	Uuid          openapi_types.UUID `json:"uuid"`
}

// SastReports defines model for SastReports.
type SastReports struct {
	Sastreports []SastReport `json:"sastreports"`
}

// UpdateSastReport defines model for UpdateSastReport.
type UpdateSastReport struct {
	Description   *string    `json:"description,omitempty"`
	Name          *string    `json:"name,omitempty"`
	ReportContent *string    `json:"reportContent,omitempty"`
	Time          *time.Time `json:"time,omitempty"`
}

// CreateSastReportJSONRequestBody defines body for CreateSastReport for application/json ContentType.
type CreateSastReportJSONRequestBody = CreateSastReport

// UpdateReportJSONRequestBody defines body for UpdateReport for application/json ContentType.
type UpdateReportJSONRequestBody = UpdateSastReport
